apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: bqv3gmvb5-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:dd11aa012e6f5060e535599431d92c318e0eb4d5@sha256:85d3b81a76f0b4d54c39ce7cba7b54a29865234e641410ad384f9c8d11cdd6ed
          name: container-image
